import { StyleSheet } from "react-native";

const createStyles = (theme) =>
  StyleSheet.create({
    scrollView: {
      flex: 1,
      backgroundColor: "#FFF8E7", // Cream/beige background
    },
    scrollContent: {
      flexGrow: 1,
    },
    container: {
      flex: 1,
      padding: 24,
      paddingTop: 32,
      backgroundColor: "#FFF8E7",
    },
    header: {
      backgroundColor: theme.colors.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    backButton: {
      padding: 8,
      width: 40,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "600",
      color: theme.staticColors.WHITE_COLOR,
      flex: 1,
      textAlign: "center",
    },
    headerSpacer: {
      width: 40,
    },
    title: {
      fontSize: 32,
      fontWeight: "bold",
      color: "#2C5282", // Blue color
      textAlign: "center",
      marginBottom: 24,
      fontFamily: theme.typography.fonts.balooPaaji,
    },
    description: {
      fontSize: 15,
      lineHeight: 22,
      color: "#4A5568",
      textAlign: "center",
      marginBottom: 32,
      paddingHorizontal: 8,
    },
    link: {
      color: "#2C5282",
      fontWeight: "600",
    },
    amountContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    currency: {
      fontSize: 48,
      fontWeight: "700",
      color: "#2C5282",
      marginRight: 8,
    },
    amountDisplay: {
      fontSize: 64,
      fontWeight: "700",
      color: "#2C5282",
      minWidth: 100,
      textAlign: "center",
    },
    perMonth: {
      fontSize: 16,
      color: "#718096",
      textAlign: "center",
      marginBottom: 24,
    },
    amountButtons: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 12,
      marginBottom: 24,
      flexWrap: "wrap",
    },
    amountButton: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: "#CBD5E0",
      backgroundColor: "transparent",
      minWidth: 70,
    },
    amountButtonSelected: {
      backgroundColor: "#2C5282",
      borderColor: "#2C5282",
    },
    amountButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#4A5568",
      textAlign: "center",
    },
    amountButtonTextSelected: {
      color: "#FFFFFF",
    },
    customAmountContainer: {
      marginBottom: 24,
      paddingHorizontal: 16,
    },
    customAmountLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: "#4A5568",
      marginBottom: 8,
      textAlign: "center",
    },
    customAmountInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "#2C5282",
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: "#FFFFFF",
    },
    customAmountCurrency: {
      fontSize: 24,
      fontWeight: "600",
      color: "#2C5282",
      marginRight: 8,
    },
    customAmountInput: {
      fontSize: 32,
      fontWeight: "600",
      color: "#2C5282",
      flex: 1,
      textAlign: "center",
      padding: 0,
    },
    frequencyContainer: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 24,
      marginBottom: 32,
    },
    frequencyOption: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    radioButton: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: "#2C5282",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    radioButtonSelected: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: "#2C5282",
    },
    frequencyText: {
      fontSize: 14,
      color: "#4A5568",
    },
    donateButton: {
      backgroundColor: "#2C5282",
      borderRadius: 25,
      paddingVertical: 14,
      paddingHorizontal: 32,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      marginBottom: 24,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
    },
    donateIconCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: "#FFFFFF",
      alignItems: "center",
      justifyContent: "center",
    },
    donateIcon: {
      fontSize: 18,
      color: "#2C5282",
    },
    donateButtonText: {
      fontSize: 18,
      fontWeight: "600",
      color: "#FFFFFF",
    },
    footerText: {
      fontSize: 13,
      color: "#718096",
      textAlign: "center",
      lineHeight: 18,
      paddingHorizontal: 24,
    },
  });

export default createStyles;
